config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'dates#show'
  resources :dates, only: [:index, :show]

  resources :tasks do
    post 'replace' => 'tasks#replace'
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base
  scope :uncompleted, -> { where(complete: false).order(priority: :desc)}
  scope :completed, -> {where(complete: true).order(completed_at: :desc)}
  scope :completed_today, -> {where(completed_at: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).order(priority: :desc)}
  validate :uncompleted_tasks_should_less_than_6
  belongs_to :user

  def self.created_today_or_uncompleted
    t = Task.arel_table
    Task.where(t[:created_at].in(Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).and(t[:complete].eq(true)).or(t[:complete].eq(false))).order(complete: :asc, priority: :desc)
  end

  def increase_priority
    self.priority = priority + 1
    self.save
    self
  end

  def decrease_priority
    new_priority = if self.priority == 0 then 0 else self.priority - 1 end
    self.priority = new_priority
    self.save
    self
  end

  def set_priority_from_index(index)
    @user = User.find(self.user_id)
    tasks = @user.tasks.uncompleted
    tasks.each_with_index do |task, i|
      if task == self
        next
      end

      if i == index
        self.priority = task.priority + 1
        self.save
      elsif i < index
        task.priority += 1
        task.save
      else
        task.priority -= 1
        task.save
      end
    end
  end

  def completed?
    self.complete == true
  end

  private

  def uncompleted_tasks_should_less_than_6
    @user = User.find(user_id)
    if self.new_record?
      if not @user.tasks.uncompleted.count <= 6
        errors.add(:task_limit, "already 6 tasks")
        false
      end
    else
      if not self.completed?
        if not @user.tasks.uncompleted.pluck(:id).include?(self.id)
          if not @user.tasks.uncompleted.count < 6
            errors.add(:task_limit, "already 6 tasks")
            false
          end
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }	
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  after_filter :discard_flash_when_ajax_request

  def json_for(target, options = {})
    target.active_model_serializer.new(target).to_json
  end

  private
    def discard_flash_when_ajax_request
      return unless request.xhr?
      flash.discard # don't want the flash to appear when you reload page
    end

    def require_login
      if not logged_in?
        flash[:danger] = t(:login_is_needed)
        redirect_to login_url
      end
    end
end

app/controllers/dates_controller.rb
class DatesController < ApplicationController
  before_action :require_login

  def index
    @incompleted_tasks = Task.uncompleted
    @completed_tasks = Task.completed
    # calendar
    @data = ActiveModel::ArraySerializer.new(Task.completed, each_serializer: TaskSerializer).to_json
  end

  def show
  	@date = l(Time.zone.now, format: "%-m월%e일(%A)")
    @task = current_user.tasks.new
    @tasks = current_user.tasks.uncompleted

    @incompleted_tasks = current_user.tasks.uncompleted
    @tasks_completed_today = current_user.tasks.completed_today
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
			log_in user
      redirect_to date_path(1)
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :change_complete_params, only: [:update]
  before_action :require_login

  def create
    respond_to do |format|
      format.js {
        @uncompleted_tasks_count = current_user.tasks.uncompleted.count
        if @uncompleted_tasks_count < 6
          task_params["priority"] = current_user.tasks.uncompleted.map(&:priority).min
          @task = Task.create!(task_params)
          @uncompleted_tasks_count += 1
          @result = :success
        else
          @result = :failed
          flash[:danger] = "You've already got 6 tasks today"
        end
      }
    end
  end

  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      format.js {
        if @task.update_attributes(task_params)
          if @task.reload.complete == true
            @task.completed_at = Time.zone.now
          else
            @task.completed_at = nil
          end
          @task.save
          @result = :success
        else
          @result = :fail
          flash[:danger] = "You've already got 6 tasks today"
        end
        @uncompleted_tasks_count = current_user.tasks.uncompleted.count
      }
    end
  end

  def destroy
    @task = Task.destroy(params[:id])
    @uncomplted_tasks_count = current_user.tasks.uncompleted.count
    respond_to do |format|
      format.js
    end
  end

  def replace
    @task = Task.find(params[:task_id])
    @task.set_priority_from_index(params[:index].to_i)
    respond_to do |format|
      format.js
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :complete, :priority, :completed_at, :user_id)
  end

  def change_complete_params
    key = params[:task].keys.find { |e| /^complete.*/ =~ e}
    val = params[:task][key]
    params[:task].delete(key)
    params[:task][:complete] = val
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dates_helper.rb
module DatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
      session[:user_id] = user.id
  end
  # Returns the current logged-in user (if any).
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
      !current_user.nil?
  end
    # Logs out the current user.
  def log_out
      session.delete(:user_id)
      @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dates/_calendar.html.erb
<!-- org code from http://bl.ocks.org/mbostock/4063318 -->

<script type='text/javascript'>
  var width = 960,
      height = 136,
      cellSize = 17; // cell size

  var percent = d3.format(".1%"),
      format = d3.time.format("%Y-%m-%d");

  var color = d3.scale.quantize()
      .domain([0, 1])
      .range(d3.range(11).map(function(d) { return "q" + d + "-11"; }));

  var svg = d3.select("#calendar-container").selectAll("svg")
      .data([2016])
    .enter().append("svg")
      .attr("width", width)
      .attr("height", height)
      .attr("class", "RdYlGn")
    .append("g")
      .attr("transform", "translate(" + ((width - cellSize * 53) / 2) + "," + (height - cellSize * 7 - 1) + ")");

  svg.append("text")
      .attr("transform", "translate(-6," + cellSize * 3.5 + ")rotate(-90)")
      .style("text-anchor", "middle")
      .text(function(d) { return d; });

  var rect = svg.selectAll(".day")
      .data(function(d) { return d3.time.days(new Date(d, 0, 1), new Date(d + 1, 0, 1)); })
    .enter().append("rect")
      .attr("class", "day")
      .attr("width", cellSize)
      .attr("height", cellSize)
      .attr("x", function(d) { return d3.time.weekOfYear(d) * cellSize; })
      .attr("y", function(d) { return d.getDay() * cellSize; })
      .datum(format);

  rect.append("title")
      .text(function(d) { return d; });

  svg.selectAll(".month")
      .data(function(d) { return d3.time.months(new Date(d, 0, 1), new Date(d + 1, 0, 1)); })
    .enter().append("path")
      .attr("class", "month")
      .attr("d", monthPath);


  var json = <%= @data.html_safe %>
  var data = d3.nest()
              .key(function(d) { return d.Date; })
              .rollup(function(d) { return (d.length / 6); })
              .map(json);

  rect.filter(function(d) { return d in data; })
      .attr("class", function(d) { return "day " + color(data[d]); })
    .select("title")
      .text(function(d) { return d + ": " + percent(data[d]); });

  function monthPath(t0) {
    var t1 = new Date(t0.getFullYear(), t0.getMonth() + 1, 0),
        d0 = t0.getDay(), w0 = d3.time.weekOfYear(t0),
        d1 = t1.getDay(), w1 = d3.time.weekOfYear(t1);
    return "M" + (w0 + 1) * cellSize + "," + d0 * cellSize
        + "H" + w0 * cellSize + "V" + 7 * cellSize
        + "H" + w1 * cellSize + "V" + (d1 + 1) * cellSize
        + "H" + (w1 + 1) * cellSize + "V" + 0
        + "H" + (w0 + 1) * cellSize + "Z";
  }
</script>

app/views/dates/index.html.erb
<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span><span>back</span>'.html_safe, root_path, class: "navigator" %>
<div class="row">
  <div class="col-md-12">
    <div id="calendar-container">
      <%= render partial: "dates/calendar", locals: {data: @data} %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <p>To-do</p>
    <div id="incompleted-tasks">
      <% @incompleted_tasks.each do |task| %>
        <%= render task %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <p>Done</p>
    <div id="today-completed-tasks">
      <% @completed_tasks.each do |task| %>
        <%= render partial: "tasks/completed", locals: {task: task} %>
      <% end %>
    </div>
  </div>
</div>

app/views/dates/show.html.erb
<div class="content-section">
  <%= render partial: "tasks/new", locals: {new_task: @task} %>
</div>

<div class="row text-center">
  <div class="col-md-6">
    <h4>
      To-do (<span id="task-num"><%= @incompleted_tasks.count %></span>/6)
    </h4>
    <div id="incompleted-tasks">
      <% @incompleted_tasks.each do |task| %>
        <%= render task %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <h4>Done</h4>
    <div id="today-completed-tasks">
      <% @tasks_completed_today.each do |task| %>
        <%= render task %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, class: "alert alert-#{message_type}") do %>
    <%= message %>
  <% end %>
<% end %>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-83926119-1', 'auto');
    ga('send', 'pageview');

  </script>
<% else %>
  <script>
    function ga () {
      var params = Array.prototype.slice.call(arguments, ga.length);
      console.log("GoogleAnalytics: " + params);
    };
  </script>
<% end %>

app/views/layouts/_meta.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily6things</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="apple-touch-icon" href="/icon.png"/>
  <link rel="shortcut icon" href="/icon.png" />
  <%= render 'layouts/meta' %>
  <%= render 'layouts/google_analytics' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main_container" class="container">
    <%= render 'layouts/flash' %>
    <% if logged_in? %>
      <div id="header-date" class="top-right"><%= @date %></div>
    <% end %>
    <!-- <div id="show-all-link" class="top-left">
      <%= link_to dates_path do %>
        <%= fa_icon "archive", text: "All Tasks" %>
      <% end %>
    </div> -->
    <%= yield %>
    <% if logged_in? %>
      <div id="footer-logout" class="bottom-left">
        <%= link_to "Logout", logout_path, method: :delete %>
      </div>
    <% end %>
    
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/tasks/_completed.html.erb
<%= form_for task, remote: true, html: {"data-priority" => task.priority } do |f| %>
  priority : <span class="task-priority" id=<%= "task-priority-#{task.id}" %>><%= "#{task.priority}" %></span>
  <% if not task.complete %>
    <%= render partial: 'tasks/up_down', locals: {task: task} %>
  <% end %>
  <%= f.check_box :complete, checked: task.complete ? true : false %>
  <%= f.label :complete, task.name %>
  <%= " (#{task.completed_at.strftime("%Y-%m-%d")})" if not task.completed_at.nil? %>
  <%= f.submit "Update" %>
  <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, task, method: :delete, remote: true, class: "pull-right delete-link" %>
<% end %>

app/views/tasks/_error.html.erb
<div id="task_errors">
  You've already got 6 tasks today
</div>

app/views/tasks/_new.html.erb
<div id="new_task">
  <%= form_for new_task, remote: true, html: {class: 'form-inline'} do |f| %>
    <div class="form-group">
      <h3><%= t(:question) %></h3>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_field :name, id: "task_input", autocomplete: "off"%>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true, html: {"data-priority" => task.priority, "data-task-id" => task.id } do |f| %>
  <% if not task.completed? %>
    <%= fa_icon "bars", class: "bar-icon" %>
  <% end %>
  <%= f.check_box "complete-#{task.id}", checked: task.complete ? true : false %>
  <%= f.label "complete-#{task.id}", task.name %>

  <% if not task.complete %>
    <%= link_to 'x', task, method: :delete, remote: true, class: "delete-link" %>
  <% end %>
  
  
<% end %>

app/views/tasks/create.js.erb
$('#task_errors').remove()

<% if @result == :success %>
  $('input#task_name').val("");
  $('#incompleted-tasks').append('<%= j render(@task) %>');
  // update task number
  $('#task-num').text('<%= @uncompleted_tasks_count %>');

  $('#edit_task_<%= @task.id %>').submitOnCheck();
<% else %>
  if ( $('.alert').length > 0) {
    $('.alert').remove();
  }
  $('#new_task').append('<%= j render("layouts/flash") %>');
<% end %>

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();
// update task number
  $('#task-num').text('<%= @uncomplted_tasks_count %>');

app/views/tasks/down.js.erb
$('span#task-priority-<%= @task.id %>').text('<%= @task.priority %>');
$('#edit_task_<%= @task.id %>').data("priority", <%= @task.priority %>);

$("#incompleted-tasks>form").each(function(){
  var prev_priority = parseInt($(this).data("priority"))
  var current_priority = <%= @task.priority %>;

  if (prev_priority > current_priority) {
    $('#edit_task_<%= @task.id %>').insertAfter($(this));
  }
});

app/views/tasks/up.js.erb
$('span#task-priority-<%= @task.id %>').text('<%= @task.priority %>');
$('#edit_task_<%= @task.id %>').data("priority", <%= @task.priority %>);

// append task according to priority
$("#incompleted-tasks>form").each(function(){
  var prev_priority = parseInt($(this).data("priority"));
  var current_priority = <%= @task.priority %>;

  if (prev_priority <= current_priority) {
    $('#edit_task_<%= @task.id %>').insertBefore($(this));
    return false
  }


});

app/views/tasks/update.js.erb
<% if @result == :success %>
  $('#edit_task_<%= @task.id %>').remove()
  // update task number
  $('#task-num').text('<%= @uncompleted_tasks_count %>');
  <% if @task.complete %>
    $('#today-completed-tasks').append('<%= j render(@task) %>');
  <% else %>
    $('#incompleted-tasks').append('<%= j render(@task) %>');
  <% end %>
  
  $('#edit_task_<%= @task.id %>').submitOnCheck();
<% else %>
  if ( $('.alert').length > 0) {
    $('.alert').remove();
  }
  $('#new_task').append('<%= j render("layouts/flash") %>');
  $('#edit_task_<%= @task.id %> input#task_complete').prop( "checked", true );
<% end %>